#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GOLDEN_DIR="${ROOT_DIR}/examples/golden-runs"

usage() {
  cat <<USAGE
Usage: $0 [--check]

Build or verify deterministic no-spend golden run bundles.
USAGE
}

CHECK_ONLY=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK_ONLY=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1 ;;
  esac
done

required_paths() {
  local bundle="$1"
  cat <<REQ
${bundle}/README.md
${bundle}/input/scout-fixture.json
${bundle}/scout.json
${bundle}/preservation.json
${bundle}/visual-gaps.json
${bundle}/shoot-plan.json
${bundle}/prompts.json
${bundle}/00-brand-analysis.md
${bundle}/01-visual-gap-audit.md
${bundle}/02-shoot-strategy.md
${bundle}/03-shot-list.md
${bundle}/04-generation-prompts.md
${bundle}/05-qa-report.md
${bundle}/06-export-map.md
${bundle}/assets/generated/generation-manifest.json
${bundle}/assets/generated/qa-results.json
${bundle}/assets/generated/reroll-manifest.json
${bundle}/assets/exports/final/export-manifest.json
${bundle}/memory/visual-profile.md
${bundle}/memory/product-shot-memory.md
${bundle}/memory/assets.md
REQ
}

check_bundle() {
  local bundle="$1"
  local missing=0
  while IFS= read -r req; do
    [[ -z "$req" ]] && continue
    if [[ ! -f "$req" ]]; then
      echo "missing: $req"
      missing=1
    fi
  done < <(required_paths "$bundle")
  return $missing
}

build_bundle() {
  local name="$1"
  local fixture="$2"
  local brand="$3"
  local product="$4"
  local bundle="${GOLDEN_DIR}/${name}"

  rm -rf "$bundle"
  mkdir -p "$bundle/input"

  cp "$fixture" "$bundle/input/scout-fixture.json"

  "${ROOT_DIR}/scripts/run-brand-shoot.py" \
    --scout-json "$fixture" \
    --brand "$brand" \
    --product "$product" \
    --out "$bundle"

  "${ROOT_DIR}/scripts/generate-images.py" --packet "$bundle"
  "${ROOT_DIR}/scripts/qa-images.py" --packet "$bundle"
  "${ROOT_DIR}/scripts/reroll-failed.py" --packet "$bundle"
  "${ROOT_DIR}/scripts/export-packager.py" --packet "$bundle" --out "$bundle/assets/exports/final"
  "${ROOT_DIR}/scripts/modules/memory_writer.py" --packet "$bundle"

  cat > "${bundle}/README.md" <<README
# ${name}

This is a dry-run golden structure bundle generated from fixture inputs with no paid API calls.

- It validates deterministic pipeline shape and artifact contracts.
- It does not prove live image quality.
- Placeholder images and deterministic QA/reroll behavior are expected.
README
}

mkdir -p "$GOLDEN_DIR"

BUNDLES=(
  "skincare-serum|${ROOT_DIR}/examples/scout-samples/skincare-serum-scout.json|Example Skin|Hydrating Face Serum"
  "coffee-roast|${ROOT_DIR}/evals/fixtures/scout-coffee.json|Alpine Goods|Summit Roast Whole Bean Coffee"
  "supplement-greens|${ROOT_DIR}/evals/fixtures/scout-supplement.json|Peak Harvest|Daily Greens Superblend"
  "cleaning-kit|${ROOT_DIR}/evals/fixtures/scout-cleaning-kit.json|BrightNest|Clean Home Essentials Kit"
)

if [[ "$CHECK_ONLY" -eq 1 ]]; then
  failures=0
  for spec in "${BUNDLES[@]}"; do
    IFS='|' read -r name _fixture _brand _product <<<"$spec"
    bundle="${GOLDEN_DIR}/${name}"
    if ! check_bundle "$bundle"; then
      failures=$((failures+1))
    fi
  done
  if [[ "$failures" -gt 0 ]]; then
    echo "golden check failed: ${failures} bundle(s) incomplete"
    exit 1
  fi
  echo "golden check passed"
  exit 0
fi

for spec in "${BUNDLES[@]}"; do
  IFS='|' read -r name fixture brand product <<<"$spec"
  build_bundle "$name" "$fixture" "$brand" "$product"
  check_bundle "${GOLDEN_DIR}/${name}"
done

cat > "${GOLDEN_DIR}/README.md" <<README
# Golden Runs

These bundles are deterministic no-spend snapshots generated by:

\`\`\`bash
./scripts/build-golden-runs.sh
\`\`\`

They are contract-shape fixtures for stage artifacts, docs, generation manifests, QA, reroll, export, and memory outputs.
They are not live-quality proof assets.
README

echo "built golden bundles in ${GOLDEN_DIR}"
